### ISSUE TITLE
problem with user saving in Mongo, and error flash

### ISSUE THREAD

**Issue by hackuun** [dchowitz/learnnode-walkthrough#1]
hi there. also doing Wes tutorial and having troubles on 24 video.

the problem is:

1. when I register user it always says 'username is expected to be unique' in flash
2. I can save **only one user** in Mongo!!! I mean - app saves to Mongo only one first user. no other user is added. 

first I thought I got errors in my code, then I found you repo. clone it - but this errors remains. is this a desired behavior? why Wes didn't mention them, I wonder? do you have ideas how to fix it?

**Comment by dchowitz** [comment]
Hmm, cannot reproduce it on my side. If I try to register an existing user again, I get "A user with the given username is already registered". Otherwise, I can register new users without problems. You can checkout https://dang.dchowitz.com/ where I've deployed the thing for some testing.

Is it possible, that something is wrong with your MongoDB schema?

**Comment by hackuun** [comment]
Strange. I just cloned your repo, as I told, so my MongoDB schema is the same.

**Comment by dchowitz** [comment]
Have you tried to delete all the data (`npm run blowitallaway`) and then reload the sample data again (`npm run sample`)?

**Comment by hackuun** [comment]
Why "again", I didn't tried to load sample data, why should I? I need to be able to create users from the form.

**Comment by hackuun** [comment]
Interesting thing, that Wes didn't even try to create SECOND user in his course. So I am pretty sure he aware of this issue and bypass this scenario in purpose. This is weird.

**Comment by dchowitz** [comment]
The app supports creating multiple users. That's for sure.

One last thought: When registering the second user, have you ensured to enter a DIFFERENT email address? Because there is a unique index on the email field in the user collection and registering different users with the same email address is prevented by design.

**Comment by hackuun** [comment]
Of course I am ensured, that's too obvious. Well, I am very disappointed and frustrated with auth implementation (which is CRUCIAL in any app) in this course, if not say least. And will drop course on this stage. Very bad move from @wesbos and there's no forum where users can discuss it (he closed Issues to repo).

Sorry for disturb.
